
package pe.upeu.edu.reporte;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ReporteImpService", targetNamespace = "http://reporte.edu.upeu.pe/", wsdlLocation = "http://localhost:5050/soap/reporte?wsdl")
public class ReporteImpService
    extends Service
{

    private final static URL REPORTEIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException REPORTEIMPSERVICE_EXCEPTION;
    private final static QName REPORTEIMPSERVICE_QNAME = new QName("http://reporte.edu.upeu.pe/", "ReporteImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5050/soap/reporte?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REPORTEIMPSERVICE_WSDL_LOCATION = url;
        REPORTEIMPSERVICE_EXCEPTION = e;
    }

    public ReporteImpService() {
        super(__getWsdlLocation(), REPORTEIMPSERVICE_QNAME);
    }

    public ReporteImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REPORTEIMPSERVICE_QNAME, features);
    }

    public ReporteImpService(URL wsdlLocation) {
        super(wsdlLocation, REPORTEIMPSERVICE_QNAME);
    }

    public ReporteImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REPORTEIMPSERVICE_QNAME, features);
    }

    public ReporteImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReporteImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReporteDao
     */
    @WebEndpoint(name = "ReporteImpPort")
    public ReporteDao getReporteImpPort() {
        return super.getPort(new QName("http://reporte.edu.upeu.pe/", "ReporteImpPort"), ReporteDao.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReporteDao
     */
    @WebEndpoint(name = "ReporteImpPort")
    public ReporteDao getReporteImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://reporte.edu.upeu.pe/", "ReporteImpPort"), ReporteDao.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REPORTEIMPSERVICE_EXCEPTION!= null) {
            throw REPORTEIMPSERVICE_EXCEPTION;
        }
        return REPORTEIMPSERVICE_WSDL_LOCATION;
    }

}
